// <auto-generated />
using System;
using Hospital_Appointment_and_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Appointment_and_Management_System.Migrations
{
    [DbContext(typeof(DoctorScheduleDbContext))]
    [Migration("20250323125405_AddDoctorSchedule")]
    partial class AddDoctorSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Appointment_and_Management_System.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.HasKey("DoctorID");

                    b.ToTable("DoctorSchedules");

                    b.HasData(
                        new
                        {
                            DoctorID = 1
                        },
                        new
                        {
                            DoctorID = 2
                        },
                        new
                        {
                            DoctorID = 3
                        },
                        new
                        {
                            DoctorID = 4
                        },
                        new
                        {
                            DoctorID = 5
                        });
                });

            modelBuilder.Entity("Hospital_Appointment_and_Management_System.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSlotID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TimeSlotID");

                    b.HasIndex("DoctorID");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            TimeSlotID = 1,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 2,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 3,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 4,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 5,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 6,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 7,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 8,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 9,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 10,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 11,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 12,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 13,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 14,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 15,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 16,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 17,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 18,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 19,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 20,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 1,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 21,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 22,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 23,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 24,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 25,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 26,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 27,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 28,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 29,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 30,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 31,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 32,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 33,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 34,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 35,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 36,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 37,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 38,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 39,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 40,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 2,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 41,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 42,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 43,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 44,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 45,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 46,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 47,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 48,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 49,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 50,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 51,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 52,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 53,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 54,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 55,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 56,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 57,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 58,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 59,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 60,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 3,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 61,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 62,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 63,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 64,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 65,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 66,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 67,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 68,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 69,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 70,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 71,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 72,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 73,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 74,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 75,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 76,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 77,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 78,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 79,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 80,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 4,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 81,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 82,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 83,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 84,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 85,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 86,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 87,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 88,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 89,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 90,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 91,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 92,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 93,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 94,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 95,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 96,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 97,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 98,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 11, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 99,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            TimeSlotID = 100,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorID = 5,
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            IsAvailable = true,
                            IsBooked = false,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Hospital_Appointment_and_Management_System.Models.TimeSlot", b =>
                {
                    b.HasOne("Hospital_Appointment_and_Management_System.Models.DoctorSchedule", "DoctorSchedule")
                        .WithMany("AvailableTimeSlots")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorSchedule");
                });

            modelBuilder.Entity("Hospital_Appointment_and_Management_System.Models.DoctorSchedule", b =>
                {
                    b.Navigation("AvailableTimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
